version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 640168440704.dkr.ecr.us-east-2.amazonaws.com
      - REPO_URI=640168440704.dkr.ecr.us-east-2.amazonaws.com/sogodemo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"sogodemo-container","imageUri":"%s"}]' "$REPO_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
